pub mod archive;pub mod commit;pub mod limits;pub mod reddit;pub mod staging;pub mod x;
use chrono::{DateTime,Utc};use serde::{Deserialize,Serialize};use uuid::Uuid;
#[derive(Debug,Clone,Copy,Serialize,Deserialize,PartialEq,Eq)]#[serde(rename_all="snake_case")]pub enum ArchivePlatform{Reddit,X}
#[derive(Debug,Clone,Copy,Serialize,Deserialize,PartialEq,Eq)]#[serde(rename_all="snake_case")]pub enum RecordType{Post,Comment,Reply,Repost,Quote}
#[derive(Debug,Clone,Copy,Serialize,Deserialize,PartialEq,Eq)]#[serde(rename_all="snake_case")]pub enum TextFormat{Standard,LongFormNote}
#[derive(Debug,Clone,Copy,Serialize,Deserialize,PartialEq,Eq)]#[serde(rename_all="snake_case")]pub enum Authorship{OwnerAuthored,Reshared}
#[derive(Debug,Clone,Copy,Serialize,Deserialize,PartialEq,Eq)]#[serde(rename_all="snake_case")]pub enum ContentState{Active,Deleted,Removed}
#[derive(Debug,Clone,Copy,Serialize,Deserialize,PartialEq,Eq)]#[serde(rename_all="snake_case")]pub enum RelationConfidence{None,Explicit,Heuristic}
#[derive(Debug,Clone,Copy,Serialize,Deserialize,PartialEq,Eq)]pub enum FormatFamily{RedditGdprCsv,XGdpr,XClassic}
#[derive(Debug,Clone,Copy,Serialize,Deserialize,PartialEq,Eq)]#[serde(rename_all="snake_case")]pub enum FormatConfidence{Confirmed,Compatible,Provisional}
#[derive(Debug,Clone,Serialize,Deserialize,PartialEq,Eq)]pub struct RecordProvenance{pub source_file:String,pub source_ordinal:u64,pub format_family:FormatFamily,pub format_confidence:FormatConfidence}
#[derive(Debug,Clone,Serialize,Deserialize,PartialEq,Eq)]pub struct NormalizedArchiveRecord{pub schema_version:u16,pub import_id:Uuid,pub platform:ArchivePlatform,pub source_logical_id:String,pub source_revision_id:String,pub record_type:RecordType,pub text_format:TextFormat,pub authorship:Authorship,pub state:ContentState,pub created_at:Option<DateTime<Utc>>,pub title:Option<String>,pub body:Option<String>,pub parent_source_id:Option<String>,pub quoted_source_id:Option<String>,pub relation_confidence:RelationConfidence,pub text_truncated:bool,pub provenance:RecordProvenance}
#[derive(Debug,Clone,Copy,PartialEq,Eq)]pub enum ImportErrorCode{UploadTooLarge,NotZip,UnsupportedZip,EncryptedZip,UnsafeZipEntry,DuplicateZipEntry,ZipLimitExceeded,UnsupportedCompression,IntegrityMismatch,NoSupportedContent,AmbiguousArchive,PlatformMismatch,UnsupportedFormatVersion,InvalidEncoding,InvalidSchema,InvalidRecord,DuplicateConflict,InvalidEditChain,AmbiguousNoteJoin,AmbiguousRevisionOrder,ResourceLimit}
impl ImportErrorCode{pub fn as_str(self)->&'static str{match self{Self::UploadTooLarge=>"upload_too_large",Self::NotZip=>"not_zip",Self::UnsupportedZip=>"unsupported_zip",Self::EncryptedZip=>"encrypted_zip",Self::UnsafeZipEntry=>"unsafe_zip_entry",Self::DuplicateZipEntry=>"duplicate_zip_entry",Self::ZipLimitExceeded=>"zip_limit_exceeded",Self::UnsupportedCompression=>"unsupported_compression",Self::IntegrityMismatch=>"integrity_mismatch",Self::NoSupportedContent=>"no_supported_content",Self::AmbiguousArchive=>"ambiguous_archive",Self::PlatformMismatch=>"platform_mismatch",Self::UnsupportedFormatVersion=>"unsupported_format_version",Self::InvalidEncoding=>"invalid_encoding",Self::InvalidSchema=>"invalid_schema",Self::InvalidRecord=>"invalid_record",Self::DuplicateConflict=>"duplicate_conflict",Self::InvalidEditChain=>"invalid_edit_chain",Self::AmbiguousNoteJoin=>"ambiguous_note_join",Self::AmbiguousRevisionOrder=>"ambiguous_revision_order",Self::ResourceLimit=>"resource_limit"}}}
#[derive(Debug,thiserror::Error)]#[error("archive rejected: {code}")]pub struct ImportError{pub code:&'static str}impl From<ImportErrorCode> for ImportError{fn from(c:ImportErrorCode)->Self{Self{code:c.as_str()}}}
