ALTER TABLE archive_imports ADD COLUMN IF NOT EXISTS raw_storage_key text;
ALTER TABLE archive_imports ADD COLUMN IF NOT EXISTS raw_storage_version_id text;
ALTER TABLE archive_imports ADD COLUMN IF NOT EXISTS archive_fingerprint bytea;
ALTER TABLE archive_imports ADD COLUMN IF NOT EXISTS fingerprint_key_version smallint;
ALTER TABLE archive_imports ADD COLUMN IF NOT EXISTS byte_size bigint;
ALTER TABLE archive_imports ADD COLUMN IF NOT EXISTS content_type text;
ALTER TABLE archive_imports ADD COLUMN IF NOT EXISTS parser_version text NOT NULL DEFAULT 'import-v1';
ALTER TABLE archive_imports ADD COLUMN IF NOT EXISTS format_family text;
ALTER TABLE archive_imports ADD COLUMN IF NOT EXISTS format_confidence text;
ALTER TABLE archive_imports ADD COLUMN IF NOT EXISTS upload_expires_at timestamptz;
ALTER TABLE archive_imports ADD COLUMN IF NOT EXISTS raw_delete_after timestamptz;
ALTER TABLE archive_imports ADD COLUMN IF NOT EXISTS raw_deleted_at timestamptz;
ALTER TABLE archive_imports ADD COLUMN IF NOT EXISTS duplicate_of_import_id uuid;
CREATE UNIQUE INDEX IF NOT EXISTS archive_imports_fingerprint_uq ON archive_imports(tenant_id,platform,archive_fingerprint) WHERE status NOT IN ('deleted','cancelled') AND archive_fingerprint IS NOT NULL;
CREATE INDEX IF NOT EXISTS archive_imports_raw_purge_idx ON archive_imports(raw_delete_after) WHERE raw_deleted_at IS NULL AND raw_storage_version_id IS NOT NULL;
ALTER TABLE content_items ADD COLUMN IF NOT EXISTS source_logical_id text;
ALTER TABLE content_items ADD COLUMN IF NOT EXISTS source_revision_id text;
ALTER TABLE content_items ADD COLUMN IF NOT EXISTS record_type text;
ALTER TABLE content_items ADD COLUMN IF NOT EXISTS text_format text;
ALTER TABLE content_items ADD COLUMN IF NOT EXISTS content_state text;
ALTER TABLE content_items ADD COLUMN IF NOT EXISTS content_hmac bytea;
ALTER TABLE content_items ADD COLUMN IF NOT EXISTS relation_confidence text;
CREATE UNIQUE INDEX IF NOT EXISTS content_items_source_uq ON content_items(tenant_id,source_logical_id) WHERE source_logical_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS import_staging_records(tenant_id uuid NOT NULL,import_id uuid NOT NULL,source_revision_id text NOT NULL,record_json jsonb NOT NULL,content_hmac bytea NOT NULL,PRIMARY KEY(tenant_id,import_id,source_revision_id),FOREIGN KEY(tenant_id,import_id) REFERENCES archive_imports(tenant_id,id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS import_index_entries(tenant_id uuid NOT NULL,import_id uuid NOT NULL,index_kind text NOT NULL,entry_key text NOT NULL CHECK(octet_length(entry_key)<=512),entry_payload bytea NOT NULL,PRIMARY KEY(tenant_id,import_id,index_kind,entry_key),FOREIGN KEY(tenant_id,import_id) REFERENCES archive_imports(tenant_id,id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS content_source_aliases(tenant_id uuid NOT NULL,source_revision_id text NOT NULL,source_logical_id text NOT NULL,PRIMARY KEY(tenant_id,source_revision_id));
CREATE TABLE IF NOT EXISTS archive_import_content_items(tenant_id uuid NOT NULL,import_id uuid NOT NULL,content_item_id uuid NOT NULL,PRIMARY KEY(tenant_id,import_id,content_item_id),FOREIGN KEY(tenant_id,import_id) REFERENCES archive_imports(tenant_id,id) ON DELETE CASCADE,FOREIGN KEY(tenant_id,content_item_id) REFERENCES content_items(tenant_id,id) ON DELETE CASCADE);
